spring.application.name=freak_e_shop

# Directorio donde se almacenan los archivos .txt de datos
app.data.dir=data

# Codificación de caracteres para Spring Boot
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Configuración de costos e impuestos
app.config.iva=19
app.config.envio=10000
